# Project: 04
# Makefile created by Dev-C++ 5.6.0

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 04.o MyRectangle2.o Screen4.o MyCircle.o
LINKOBJ  = 04.o MyRectangle2.o Screen4.o MyCircle.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = 04.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

04.o: 04.cpp
	$(CPP) -c 04.cpp -o 04.o $(CXXFLAGS)

MyRectangle2.o: MyRectangle2.cpp
	$(CPP) -c MyRectangle2.cpp -o MyRectangle2.o $(CXXFLAGS)

Screen4.o: Screen4.cpp
	$(CPP) -c Screen4.cpp -o Screen4.o $(CXXFLAGS)

MyCircle.o: MyCircle.cpp
	$(CPP) -c MyCircle.cpp -o MyCircle.o $(CXXFLAGS)
